//! Android AIDL (Binder IPC) interface for the mycelium node.
//!
//! Compiled only when rustc is invoked with `--cfg aidl` (set by the Soong
//! build — there is no Cargo feature for it). The AIDL bindings come from the
//! `mycelium_aidl_interface` Rust crate generated by Soong's `aidl_interface`
//! module, and the Binder runtime comes from AOSP's `libbinder_rs` (the
//! `binder` crate).

mod conversions;
mod service;

pub use service::MyceliumService;

pub use mycelium_aidl_interface::aidl::tech::threefold::mycelium::IMyceliumService::{
    BnMyceliumService, IMyceliumService,
};
