fn main() {
    let out_dir = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let output = out_dir.join("mycelium_aidl.rs");

    rsbinder_aidl::Builder::new()
        .source("aidl/tech/threefold/mycelium/PeerInfo.aidl")
        .source("aidl/tech/threefold/mycelium/NodeInfo.aidl")
        .source("aidl/tech/threefold/mycelium/Route.aidl")
        .source("aidl/tech/threefold/mycelium/QueriedSubnet.aidl")
        .source("aidl/tech/threefold/mycelium/PacketStatEntry.aidl")
        .source("aidl/tech/threefold/mycelium/PacketStats.aidl")
        .source("aidl/tech/threefold/mycelium/IMyceliumService.aidl")
        .output(&output)
        .generate()
        .unwrap();

    // rsbinder-aidl 0.6.0 generates async infrastructure that is incompatible with
    // async-trait ≥ 0.1.80 on Rust ≥ 1.75 (native AFIT makes async traits non-dyn-compatible).
    // We can't pin async-trait < 0.1.80 because mycelium requires ^0.1.89.
    patch_async_compat(&output);

    println!("cargo:rerun-if-changed=aidl/");
}

/// Fix the generated code so it compiles with modern async-trait.
///
/// Two issues:
///
/// 1. `IXxxAsyncService` is annotated `#[async_trait]` with `async fn` methods.
///    With async-trait ≥ 0.1.80 on Rust ≥ 1.75 the macro uses native AFIT, making the
///    trait non-dyn-compatible. The adapter generated by `declare_binder_interface!`
///    requires `&dyn IXxxAsyncService`, so we rewrite every `async fn` to return a
///    `BoxFuture` instead — which is dyn-compatible.
///
/// 2. The `impl BnXxx { pub fn new_async_binder ... }` block forward-references
///    `BnXxx` before `declare_binder_interface!` defines it, causing E0425.
///    We remove the block since we only use `new_binder`.
fn patch_async_compat(path: &std::path::Path) {
    let src = std::fs::read_to_string(path).expect("read generated AIDL file");

    // Step 1 — Strip #[async_trait] from the AsyncService trait.
    let patched = src.replace("#[::async_trait::async_trait]\n", "");

    // Step 2 — Rewrite every `async fn r#name(params) -> RetType;` found in the file
    // (only IXxxAsyncService uses async fn in rsbinder-aidl generated code).
    // Each `&` in the parameter list gets a `'a` lifetime; the return type is wrapped
    // in BoxFuture<'a, _>.  Method names keep the `r#` raw-identifier prefix.
    let async_fn_re =
        regex::Regex::new(r"(?m)^(\s+)async fn (r#\w+)\(([^)]+)\)\s*->\s*([^;]+);$").unwrap();

    let patched = async_fn_re
        .replace_all(&patched, |caps: &regex::Captures| {
            let indent = &caps[1];
            let name = &caps[2];
            // Add 'a lifetime to every reference parameter, but leave &self untouched.
            // Workaround: replace &self with a unique marker before adding 'a, then restore it.
            let params = caps[3]
                .replace("&self", "\x00SELF\x00")
                .replace('&', "&'a ")
                .replace("\x00SELF\x00", "&self");
            let ret = caps[4].trim();
            format!("{indent}fn {name}<'a>({params}) -> rsbinder::BoxFuture<'a, {ret}>;")
        })
        .into_owned();

    // Step 3 — Remove `impl BnXxx { pub fn new_async_binder ... }`.
    // The block starts with `impl Bn<ServiceName>` and ends just before
    // `pub trait IXxxDefault`.  Use the stable suffixes that rsbinder-aidl always emits.
    let patched = remove_between(patched, "            impl Bn", "            pub trait I");

    std::fs::write(path, patched).expect("write patched AIDL file");
}

/// Remove the text from the first occurrence of `start_marker` up to (but not
/// including) the first occurrence of `end_marker` that follows it.
fn remove_between(src: String, start_marker: &str, end_marker: &str) -> String {
    match (src.find(start_marker), src.find(end_marker)) {
        (Some(start), Some(end)) if start < end => {
            format!("{}{}", &src[..start], &src[end..])
        }
        _ => src,
    }
}
