// Generated by cbindgen — do not edit.

#ifndef MYCELIUM_H
#define MYCELIUM_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/*
 The prefix length of the global subnet used.
 */
#define GLOBAL_SUBNET_PREFIX_LEN 7

/*
 Operation succeeded.
 */
#define MYCELIUM_OK 0

/*
 One of the arguments was invalid (null, out-of-range, malformed UTF-8, …).
 */
#define MYCELIUM_ERR_INVALID_ARG -1

/*
 The node is in the wrong state for this operation (e.g. start while
 running, or query while stopped).
 */
#define MYCELIUM_ERR_INVALID_STATE -2

/*
 An internal failure surfaced from the underlying node implementation.
 */
#define MYCELIUM_ERR_INTERNAL -3

/*
 Default SOCKS5 port used when listing known proxies.
 */
#define DEFAULT_SOCKS_PORT 1080

/*
 Size in bytes of a `RouterId`
 */
#define RouterId_BYTE_SIZE 40

/*
 Opaque handle to a running (or stopped) mycelium node.

 Created by [`mycelium_start`](super::mycelium_start), released by
 [`mycelium_node_free`](super::mycelium_node_free). The C side only ever
 sees an opaque pointer — cbindgen emits a forward declaration for this
 struct because it is not `#[repr(C)]`.
 */
typedef struct mycelium_node_t mycelium_node_t;

/*
 Configuration passed to `mycelium_start`. The library reads strings out
 during the call and does not retain any of the pointers — caller still
 owns the memory.
 */
typedef struct mycelium_start_config_t {
  /*
   32-byte node secret key.
   */
  uint8_t priv_key[32];
  /*
   Array of bootstrap peer endpoints (NUL-terminated UTF-8).
   */
  const char *const *peers;
  /*
   Number of entries in `peers`.
   */
  uintptr_t peers_len;
  /*
   Enable the embedded DNS resolver.
   */
  bool enable_dns;
  /*
   TCP listen port.
   */
  uint16_t tcp_listen_port;
  /*
   QUIC listen port; 0 disables QUIC.
   */
  uint16_t quic_listen_port;
  /*
   UDP port for peer discovery.
   */
  uint16_t peer_discovery_port;
  /*
   Discovery mode: "all", "disabled", or "filtered".
   */
  const char *peer_discovery_mode;
  /*
   When mode is "filtered", the allow-list of interface names.
   */
  const char *const *peer_discovery_interfaces;
  /*
   Number of entries in `peer_discovery_interfaces`.
   */
  uintptr_t peer_discovery_interfaces_len;
  /*
   Name of the TUN device.
   */
  const char *tun_name;
  /*
   Pre-opened TUN file descriptor. Required on iOS and on macOS when
   the `mactunfd` feature is enabled (the platform delivers the fd
   through Network Extensions / app-store sandbox plumbing). Ignored
   on Linux, Windows, plain macOS, and Android — Android opens
   `/dev/tun` itself from `tun_name`.
   */
  int32_t tun_fd;
} mycelium_start_config_t;

/*
 Public node identity.
 */
typedef struct mycelium_node_info_t {
  char *subnet;
  char *pubkey;
} mycelium_node_info_t;

/*
 Information about a known peer connection.
 */
typedef struct mycelium_peer_info_t {
  char *protocol;
  char *address;
  char *peer_type;
  char *connection_state;
  int64_t rx_bytes;
  int64_t tx_bytes;
  int64_t discovered_seconds;
  /*
   `-1` if the peer was never connected.
   */
  int64_t last_connected_seconds;
} mycelium_peer_info_t;

typedef struct mycelium_peer_info_array_t {
  struct mycelium_peer_info_t *items;
  uintptr_t len;
} mycelium_peer_info_array_t;

/*
 A route entry (selected or fallback).
 */
typedef struct mycelium_route_t {
  char *subnet;
  char *next_hop;
  /*
   `-1` means infinite metric.
   */
  int64_t metric;
  int32_t seqno;
} mycelium_route_t;

typedef struct mycelium_route_array_t {
  struct mycelium_route_t *items;
  uintptr_t len;
} mycelium_route_array_t;

/*
 A subnet currently being queried by the routing layer.
 */
typedef struct mycelium_queried_subnet_t {
  char *subnet;
  int64_t expiration_seconds;
} mycelium_queried_subnet_t;

typedef struct mycelium_queried_subnet_array_t {
  struct mycelium_queried_subnet_t *items;
  uintptr_t len;
} mycelium_queried_subnet_array_t;

/*
 Per-IP packet counter entry.
 */
typedef struct mycelium_packet_stat_entry_t {
  char *ip;
  int64_t packet_count;
  int64_t byte_count;
} mycelium_packet_stat_entry_t;

/*
 Aggregated packet statistics.
 */
typedef struct mycelium_packet_stats_t {
  struct mycelium_packet_stat_entry_t *by_source;
  uintptr_t by_source_len;
  struct mycelium_packet_stat_entry_t *by_destination;
  uintptr_t by_destination_len;
} mycelium_packet_stats_t;

/*
 32-byte secret key (output of `mycelium_generate_secret_key`).
 */
typedef struct mycelium_secret_key_t {
  uint8_t bytes[32];
} mycelium_secret_key_t;

typedef struct mycelium_string_array_t {
  char **items;
  uintptr_t len;
} mycelium_string_array_t;

/*
 Returns the last error message produced on this thread, or NULL if there
 is none. The returned pointer is owned by the library and remains valid
 only until the next FFI call from the same thread.
 */
const char *mycelium_last_error_message(void);

/*
 Start a mycelium node. Returns an opaque handle on success, or NULL on
 failure — call `mycelium_last_error_message` for details. The returned
 handle must eventually be released with `mycelium_node_free`.

 # Safety

 `cfg` must point to a fully-initialised `mycelium_start_config_t`.
 Pointer fields inside (`peers`, `peer_discovery_mode`,
 `peer_discovery_interfaces`, `tun_name`) follow the conventions in the
 module-level safety docs. The struct and any strings it points at are
 not retained beyond the call — the caller may free them as soon as
 this function returns.
 */
struct mycelium_node_t *mycelium_start(const struct mycelium_start_config_t *cfg);

/*
 Halt the node and release its internal resources. The handle remains
 valid for `mycelium_is_running` queries (which will return false) until
 `mycelium_node_free` is called. No-op on an already-stopped node.

 # Safety

 `node` must be NULL or a live handle returned by `mycelium_start`.
 */
int32_t mycelium_stop(struct mycelium_node_t *node);

/*
 Write `true`/`false` into `out` reflecting whether the node is running.

 # Safety

 `node` must be a live handle returned by `mycelium_start`. `out` must
 point to a writable, properly aligned `bool`.
 */
int32_t mycelium_is_running(struct mycelium_node_t *node, bool *out);

/*
 Populate `out` with the node's subnet and public key. The returned
 strings are owned by the caller and must be released with
 `mycelium_node_info_free`.

 # Safety

 `node` must be a live handle returned by `mycelium_start`. `out` must
 point to a writable, properly aligned `mycelium_node_info_t`. Any
 previous contents of `*out` are overwritten without being freed —
 callers must release prior contents first or pass a fresh struct.
 */
int32_t mycelium_get_node_info(struct mycelium_node_t *node, struct mycelium_node_info_t *out);

/*
 Look up the public key of the peer that owns the given mycelium IP.
 On success writes a newly-allocated string to `*out` (empty if no
 match); release with `mycelium_string_free`.

 # Safety

 `node` must be a live handle returned by `mycelium_start`. `ip` must
 be a NUL-terminated C string. `out` must point to a writable
 `*mut c_char`.
 */
int32_t mycelium_get_public_key_from_ip(struct mycelium_node_t *node, const char *ip, char **out);

/*
 Populate `out` with one entry per known peer. Release the array with
 `mycelium_peer_info_array_free`.

 # Safety

 `node` must be a live handle returned by `mycelium_start`. `out` must
 point to a writable, properly aligned `mycelium_peer_info_array_t`;
 any previous contents are overwritten without being freed.
 */
int32_t mycelium_get_peers(struct mycelium_node_t *node, struct mycelium_peer_info_array_t *out);

/*
 Add a peer endpoint. Writes `true` to `*out` if the peer was newly
 added, `false` if it was already known.

 # Safety

 `node` must be a live handle returned by `mycelium_start`. `endpoint`
 must be a NUL-terminated C string. `out` must point to a writable
 `bool`.
 */
int32_t mycelium_add_peer(struct mycelium_node_t *node, const char *endpoint, bool *out);

/*
 Remove a peer endpoint. Writes `true` to `*out` if the peer existed
 and was removed, `false` if no such peer was registered.

 # Safety

 `node` must be a live handle returned by `mycelium_start`. `endpoint`
 must be a NUL-terminated C string. `out` must point to a writable
 `bool`.
 */
int32_t mycelium_remove_peer(struct mycelium_node_t *node, const char *endpoint, bool *out);

/*
 Populate `out` with the currently selected (in-use) routes. Release
 the array with `mycelium_route_array_free`.

 # Safety

 `node` must be a live handle returned by `mycelium_start`. `out` must
 point to a writable, properly aligned `mycelium_route_array_t`; any
 previous contents are overwritten without being freed.
 */
int32_t mycelium_get_selected_routes(struct mycelium_node_t *node,
                                     struct mycelium_route_array_t *out);

/*
 Populate `out` with the routing table's fallback (non-selected) routes.
 Release the array with `mycelium_route_array_free`.

 # Safety

 `node` must be a live handle returned by `mycelium_start`. `out` must
 point to a writable, properly aligned `mycelium_route_array_t`; any
 previous contents are overwritten without being freed.
 */
int32_t mycelium_get_fallback_routes(struct mycelium_node_t *node,
                                     struct mycelium_route_array_t *out);

/*
 Populate `out` with subnets the router is currently querying. Release
 the array with `mycelium_queried_subnet_array_free`.

 # Safety

 `node` must be a live handle returned by `mycelium_start`. `out` must
 point to a writable, properly aligned `mycelium_queried_subnet_array_t`;
 any previous contents are overwritten without being freed.
 */
int32_t mycelium_get_queried_subnets(struct mycelium_node_t *node,
                                     struct mycelium_queried_subnet_array_t *out);

/*
 Populate `out` with aggregated packet statistics. Release with
 `mycelium_packet_stats_free`.

 # Safety

 `node` must be a live handle returned by `mycelium_start`. `out` must
 point to a writable, properly aligned `mycelium_packet_stats_t`; any
 previous contents are overwritten without being freed.
 */
int32_t mycelium_get_packet_stats(struct mycelium_node_t *node,
                                  struct mycelium_packet_stats_t *out);

/*
 Generate a fresh 32-byte node secret key into `out`. Stateless — no
 node handle required.

 # Safety

 `out` must point to a writable, properly aligned
 `mycelium_secret_key_t`.
 */
int32_t mycelium_generate_secret_key(struct mycelium_secret_key_t *out);

/*
 Derive the mycelium address (text form) of the public key for the
 given secret key. Writes a newly-allocated string to `*out`; release
 with `mycelium_string_free`. Stateless — no node handle required.

 # Safety

 `key` must point to an initialised `mycelium_secret_key_t`. `out` must
 point to a writable `*mut c_char`.
 */
int32_t mycelium_address_from_secret_key(const struct mycelium_secret_key_t *key, char **out);

/*
 Begin the periodic SOCKS5 proxy probe scan.

 # Safety

 `node` must be a live handle returned by `mycelium_start`.
 */
int32_t mycelium_start_proxy_probe(struct mycelium_node_t *node);

/*
 Stop the periodic SOCKS5 proxy probe scan.

 # Safety

 `node` must be a live handle returned by `mycelium_start`.
 */
int32_t mycelium_stop_proxy_probe(struct mycelium_node_t *node);

/*
 List the currently known SOCKS5 proxy endpoints (formatted as
 `addr:port` strings). Release with `mycelium_string_array_free`.

 # Safety

 `node` must be a live handle returned by `mycelium_start`. `out` must
 point to a writable, properly aligned `mycelium_string_array_t`; any
 previous contents are overwritten without being freed.
 */
int32_t mycelium_list_proxies(struct mycelium_node_t *node, struct mycelium_string_array_t *out);

/*
 Connect to a remote SOCKS5 proxy. Writes the negotiated remote address
 to `*out` as a newly-allocated string; release with
 `mycelium_string_free`.

 # Safety

 `node` must be a live handle returned by `mycelium_start`. `remote`
 must be a NUL-terminated C string. `out` must point to a writable
 `*mut c_char`.
 */
int32_t mycelium_proxy_connect(struct mycelium_node_t *node, const char *remote, char **out);

/*
 Disconnect from the currently connected SOCKS5 proxy, if any.

 # Safety

 `node` must be a live handle returned by `mycelium_start`.
 */
int32_t mycelium_proxy_disconnect(struct mycelium_node_t *node);

/*
 Release a node handle returned by `mycelium_start`. If the node is still
 running it is stopped first. Safe to call with NULL.

 # Safety

 `node` must be NULL or a pointer previously returned by `mycelium_start`
 that has not already been passed to this function. Double-free or
 use-after-free is undefined behaviour.
 */
void mycelium_node_free(struct mycelium_node_t *node);

/*
 Free a single C string returned by the library. Safe to call with NULL.

 # Safety

 `ptr` must be NULL or a value returned by a `mycelium_*` entry point
 that hands the caller ownership of a `char *` (e.g.
 `mycelium_get_public_key_from_ip`, `mycelium_address_from_secret_key`,
 `mycelium_proxy_connect`). Strings retrieved via `mycelium_last_error_message`
 are owned by the library and must NOT be passed here.
 */
void mycelium_string_free(char *ptr);

/*
 Free a string array returned by the library. The outer struct is
 caller-allocated; this releases the items and the backing storage, then
 resets `items` to NULL and `len` to 0.

 # Safety

 `arr` must be NULL or point to a `mycelium_string_array_t` populated by
 a successful library call (currently only `mycelium_list_proxies`).
 Calling this twice on the same struct is safe — the second call sees
 `items == NULL` and does nothing.
 */
void mycelium_string_array_free(struct mycelium_string_array_t *arr);

/*
 Free a `mycelium_node_info_t` populated by `mycelium_get_node_info`.
 Releases the inner `subnet` and `pubkey` strings and resets them to
 NULL.

 # Safety

 `info` must be NULL or point to a struct populated by a successful call
 to `mycelium_get_node_info`. Calling this twice on the same struct is
 safe — the second call sees the fields already NULL.
 */
void mycelium_node_info_free(struct mycelium_node_info_t *info);

/*
 Free a peer-info array populated by `mycelium_get_peers`. Releases each
 item's strings, then the backing array, then resets the struct.

 # Safety

 `arr` must be NULL or point to a `mycelium_peer_info_array_t` populated
 by a successful call to `mycelium_get_peers`. Idempotent.
 */
void mycelium_peer_info_array_free(struct mycelium_peer_info_array_t *arr);

/*
 Free a route array populated by `mycelium_get_selected_routes` or
 `mycelium_get_fallback_routes`.

 # Safety

 `arr` must be NULL or point to a `mycelium_route_array_t` populated by
 a successful call to one of those two functions. Idempotent.
 */
void mycelium_route_array_free(struct mycelium_route_array_t *arr);

/*
 Free a queried-subnet array populated by `mycelium_get_queried_subnets`.

 # Safety

 `arr` must be NULL or point to a `mycelium_queried_subnet_array_t`
 populated by a successful call to `mycelium_get_queried_subnets`.
 Idempotent.
 */
void mycelium_queried_subnet_array_free(struct mycelium_queried_subnet_array_t *arr);

/*
 Free a `mycelium_packet_stats_t` populated by
 `mycelium_get_packet_stats`. Releases both the by-source and
 by-destination arrays.

 # Safety

 `stats` must be NULL or point to a `mycelium_packet_stats_t` populated
 by a successful call to `mycelium_get_packet_stats`. Idempotent.
 */
void mycelium_packet_stats_free(struct mycelium_packet_stats_t *stats);

#endif  /* MYCELIUM_H */
